# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20161023_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('pub_data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DN', 'Do now'), ('WD', 'Will do'), ('HF', 'Help friends'), ('D', 'Done')], default='WD', max_length=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('helpers', models.ManyToManyField(related_name='helpers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='author',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='helpers',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AlterField(
            model_name='star',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
