# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20161101_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('pub_data',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
