# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='done_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='will_do_task',
            field=models.IntegerField(default=0),
        ),
    ]
